/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

export const CAT_LOADING_PHRASES: readonly string[] = [
  'Chasing a laser pointer through the codebase…',
  'Knocking variables off the desk…',
  'Sitting in a box of functions…',
  'Kneading the algorithms into shape…',
  'Judging your code silently…',
  'Staring at the wall for exactly 3 minutes…',
  'Knocking that bug off the table…',
  'Contemplating whether to push to main…',
  'Pretending to sleep while actually processing…',
  'Knocking over your coffee for inspiration…',
  'Demanding attention before delivering results…',
  'Hunting the elusive segfault…',
  'Bathing paws before touching clean code…',
  'Claiming the keyboard as territory…',
  'Pushing a glass of recursion to the edge…',
  'Meowing at the compiler until it cooperates…',
  'Sitting on the warm server for comfort…',
  'Slowly blinking in approval of your prompt…',
  'Making biscuits out of the heap memory…',
  'Fleeing in terror from the vacuum cleaner process…',
  'Curled up in a tight loop for warmth…',
  'Pawing at the network socket…',
  'Loudly vocalizing at 3 AM for no reason…',
  'Bringing you a dead bug as a present…',
  'Refusing to move until the computation is done…',
  'Chattering at birds in the dependency tree…',
  'Zooming across the file system at 2 AM…',
  'Hairballing the error logs…',
  'Squeezing into a container that is clearly too small…',
  'Ignoring your calls but watching your keystrokes…',
  'Teleporting to a different room of the codebase…',
  'Sniffing suspiciously at the new framework…',
  'Gracefully landing on all four paws after that stack trace…',
  'Purrfectly parallelizing the threads…',
  'Grooming the syntax until it shines…',
  'Tail held high as the build succeeds…',
  'Leaving a paw print on every file touched…',
  'Nine lives of retry logic activated…',
  'Napping between requests for peak performance…',
  'Whiskers twitching — detecting undefined behavior…',
  'Ears flattened — parsing your ambiguous prompt…',
  'Marking this scope as my territory…',
  'Pouncing on that edge case…',
  'Chirping at the API endpoint…',
];

export const CAT_TASK_LABELS: readonly string[] = [
  'Pouncing on it…',
  'On the hunt…',
  'Whiskers working…',
  'Purring through it…',
  'Pawing at the problem…',
  'Tail twitching — almost there…',
  'Task in progress…',
  'Kneading the solution…',
  'Sniffing out an answer…',
  'Ears perked — processing…',
];
